# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/cli/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/common/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/create-flux/" # Location of package manifests
    schedule:
      interval: "monthly"
