name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: |
        npm install -g pnpm
        pnpm install
        pnpm -r --filter='./packages/*' build
        cd ./packages/integration-tests
        pnpm run dev &
        sleep 5
        pnpm run test
